# Generated by Django 5.1.5 on 2025-02-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
