# Generated by Django 5.1.5 on 2025-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='descuento',
        ),
        migrations.AddField(
            model_name='descuento',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
